### ISSUE TITLE
add Github Auth

### ISSUE THREAD

**Issue by szuecs** [zalando/gin-oauth2#18]
It should be possible to use Github OAuth2 infrastructure with this middleware.

**Comment by LappleApple** [comment]
Hey @szuecs, still want this?  Want to add a Help Wanted label?

**Comment by szuecs** [comment]
@LappleApple sure I want to have it. :)

**Comment by LappleApple** [comment]
@szuecs +1 for the HW label.

**Comment by njuettner** [comment]
This issue is fixed in #39
