### ISSUE TITLE
Google OAuth example

### ISSUE THREAD

**Issue by carljmosca** [zalando/gin-oauth2#41]
Is there a working example which includes the refresh token?

**Comment by szuecs** [comment]
@carljmosca no, but I would be happy to merge changes to the google provider. 

I am not sure how you would like to have the refresh token in a web application. As far as I know you would use the refresh token to get a renewed access token and the web application will only validate the access token from the user using one of many OAuth flows.

**Comment by szuecs** [comment]
no answer to my question -> close
