### ISSUE TITLE
RequestAuthInfo with Auth header?

### ISSUE THREAD

**Issue by eloo** [zalando/gin-oauth2#43]
Hi,

i've just tested your implementation and discovered that the RequestAuthInfo function can only be used if the AuthInfo endpoint of my Oauth2 server is using the access_token parameter.
So my question is what is about other servers like keycloak which are using the Auth header for passing the bearer.

Can this lib uses with keycloak for example?

**Comment by szuecs** [comment]
@eloo Good question, I am not sure but am open to accept changes of RequestAuthInfo.
Does the keycloak case work if we just add the Token into the header Authorization: Bearer <token> ?
If it does not and we have to branch I have to think more about your case.

**Comment by eloo** [comment]
@szuecs thanks for your fast response.. and yes i will test it and give feedback or PR

**Comment by eloo** [comment]
@szuecs okay.. i've tested it to simply add the token as header but it seems that there is more to be changed.
maybe this is not the right way for my usecase
