### ISSUE TITLE
Invalid session state in github example

### ISSUE THREAD

**Issue by bonifaido** [zalando/gin-oauth2#45]
Hi, I wanted to try out the GitHub example, and after a successful login I have navigated to the /auth/api endpoint but got an error message, is this the expected behaviour? Thanks!
```
[GIN] 2018/01/09 - 15:07:15 | 401 |     132.011µs | 127.0.0.1 |   GET     /auth/api
Error #01: Invalid session state: ***********
```

**Comment by szuecs** [comment]
@bonifaido Did you replaced the content of test-clientid.github.json ?
I am not sure, because I never tested it and I don't use it, but I would be happy to merge all PRs that fixes it for you.

**Comment by bonifaido** [comment]
Yes, I have replaced it, and the login was successful I got back my own user information, but after that accessing the `/api` endpoint gives me 401.

**Comment by szuecs** [comment]
@bonifaido I checked the example and it works for me

My steps:
1. https://github.com/settings/applications/new register app
2. replace the fields in the json file with the one from the registered app
3.  go run example/github/github.go
4. open browser at http://127.0.0.1:8081/auth/
5. select my GH user to authorize and got redirected and authorized sucessfully

[sszuecs@sandor-lab:~/go/src/github.com/zalando/gin-oauth2]% go run example/github/github.go
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /login                    --> github.com/zalando/gin-oauth2/github.LoginHandler (4 handlers)
[GIN-debug] GET    /auth/                    --> main.UserInfoHandler (5 handlers)
[GIN-debug] GET    /auth/api                 --> main.main.func1 (5 handlers)
[GIN-debug] Listening and serving HTTP on 127.0.0.1:8081
[GIN] 2018/01/10 - 09:51:12 | 200 |     420.545µs |       127.0.0.1 |  GET     /login
[GIN] 2018/01/10 - 09:51:13 | 404 |       6.467µs |       127.0.0.1 |  GET     /favicon.ico
[GIN] 2018/01/10 - 09:51:13 | 404 |       6.776µs |       127.0.0.1 |  GET     /favicon.ico
[GIN] 2018/01/10 - 09:51:13 | 404 |       7.076µs |       127.0.0.1 |  GET     /favicon.ico
[GIN] 2018/01/10 - 09:51:29 | 200 |  1.145859968s |       127.0.0.1 |  GET     /auth/

Hope this helps

**Comment by bonifaido** [comment]
Thank you for looking into this.
My steps looked very similar, can you access `/auth/api` after the login procedure?

**Comment by szuecs** [comment]
No I can not /auth/api gives me a 404. I am not sure why, but this could be in the session middleware which is used. You might want to look into that. The oauth2 flow seems to work.
I would be happy if you find the issue in the session, maybe we use it wrong.

**Comment by fronbasal** [comment]
I am experiencing the same issue. This is a provider-related issue.
I have tried to implement my own provider with the GitHub provider as a template which resulted in the behaviour described above.

**Comment by weeee9** [comment]
Is there any solution to this? I'm getting same problem.

**Comment by szuecs** [comment]
@weeee9 @fronbasal would you share some code example, that shows the problem, please?

**Comment by weeee9** [comment]
@szuecs my code is same as the Goolge example, and I knew that the problem is in the `Auth()` HandlerFunc, not sure is problem with `session.Get("state")` or `ctx.query("state")`.

**Comment by szuecs** [comment]
@weeee9 thanks for reporting. I think it's basically this issue: https://github.com/zalando/gin-oauth2/issues/57 
Github provider will always do the Authorization flow.
