### ISSUE TITLE
Invalid cast in case of scope != uid

### ISSUE THREAD

**Issue by rgritti** [zalando/gin-oauth2#48]
In case you have a token with scope = "nakadi.event_stream.read" the payload from the tokeninfo endpoint is the following:
```
{
    "access_token":"dyU...xVM",
    "client_id":"stups_marilyn-updater_ec462cc5-3861-4873-9f91-001549db1aaa",
    "expires_in":2605,
    "grant_type":"password",
    "nakadi.event_stream.read":true,
    "realm":"/services",
    "scope":[
        "nakadi.event_stream.read",
        "uid"
    ],
    "token_type":"Bearer",
    "uid":"stups_marilyn-updater"
}
```
in [ParseTokenContainer](https://github.com/zalando/gin-oauth2/blob/master/ginoauth2.go#L140-L147) the following code parse the payload
```
scopes := data["scope"].([]interface{})
for _, scope := range scopes {
	sscope := scope.(string)
	sval, ok := data[sscope]
	if ok {
		tdata[sscope] = sval
	}
}
```
The above code creates a map[string]interface{} that in the case of the example payload above, it will be:
```
tdata["uid"] = "stups_marilyn-updater"
tdata["nakadi.event_stream.read"] = true
```

the [zalando.ScopeCheck](https://github.com/zalando/gin-oauth2/blob/master/zalando/zalando.go#L134) takes the map and cast the value to string:
```
if cur, ok := tc.Scopes[s].(string); ok {
	glog.V(2).Infof("Found configured scope %s", cur)
	scopesFromToken = append(scopesFromToken, cur)
	ctx.Set(s, cur) // set value from token of configured scope to the context, which you can use in your application.
}
```

This cause the ok to be != true and the scope check to fail

**Comment by szuecs** [comment]
thanks @rgritti
