### ISSUE TITLE
using to create a oauth2 provider

### ISSUE THREAD

**Issue by moos3** [zalando/gin-oauth2#55]
I'm wondering if I can use this to be a provider for Oauth 2.0 applications. If so is there an example somewhere on this? Basically, we are trying to mimic like the GitHub OAuth Apps, where the user clicks a button to create a new application, they get a client id and secret given to them and they can update call back URL or refresh the secret.  Every google search brings me here for gin and OAuth. Help, please :) I have the db model done its pretty simple, just not sure how to integrate this in or where to start with it. As all the examples are using a provider and not being a provider.

**Comment by szuecs** [comment]
No it's validation only.
I guess you want to try something like [dex](https://github.com/dexidp/dex)
