### ISSUE TITLE
What this library implements seems not to be an OAuth "Authorisation Code Grant" standard flow. Please comment.

### ISSUE THREAD

**Issue by Muzietto** [zalando/gin-oauth2#57]
We are trying to use GitHub as authorisation server for our app called "one". 
We are unable to use successfully the browser to retrieve server resources (even though we specify `code` and `state` in each request). We are currently able to retrieve resources only using cURL.

There are two major things while attempting to use this library that we cannot find anywhere in the official OAUTH documentations resp. inside available online resources:

- we never see any token flowing back and forth between our backend equipped with your library and the browser. On the contrary, we see that apparently the token is "rebuilt" at each GET done by the browser (https://github.com/zalando/gin-oauth2/blob/master/github/github.go#L84)

- we do see a cookie "one_session_github" that arrives in the browser after the redirect following the OK given by the user on GitHub. This cookie is mandatory and without it not even our cURL resource requests may succeed.

We are having a real hard time using your library. Can you please help investigating our case? 
Thank you for your attention.

**Comment by Muzietto** [comment]
A possibly relevant point is that our back-end has a domain name different from our front-end. We had to face some CORS issues in order to get the cookie, but they are now solved.

**Comment by szuecs** [comment]
@Muzietto I am sorry that you have a hard time to use it. I thought it makes sense to have a general implementation and then providers, but the problem is testing all providers is not easily possible.
The colleague that implemented this part is in vacation and I can not ask him what kind of goal he had and what scope he tested.

We did not implemented the "Authorisation Code Grant" flow, we only support checking scopes. I think we do not support really UI flows.

**Comment by Muzietto** [comment]
What you write confuses me, because it is your README that at https://github.com/zalando/gin-oauth2#github-based-access explicitly mentions "This OAuth2 flow is also known as Authorization Code Flow".

The link provided in "Authorization Code Flow" sends to https://tools.ietf.org/html/rfc6749#section-4.1, which is indeed the Code Grant thing.

**Comment by szuecs** [comment]
Sorry then I was wrong. 
As far as I understand the problem is that the session is not handled correctly.
So the flow works but in a second request the flow starts again.
Do I understand you correctly?
