### ISSUE TITLE
Invalid session state google example

### ISSUE THREAD

**Issue by abit2** [zalando/gin-oauth2#66]
Hi, I wanted to try out the Google example, and after a successful login I have navigated to the /auth/api endpoint but got an error message, is this the expected behaviour? Thanks!

```
[GIN] 2021/03/07 - 14:55:29 | 401 |     108.714µs |             ::1 | GET      "/auth/api"
Error #01: Invalid session state: *********************************
```

Seems like an issue similar to https://github.com/zalando/gin-oauth2/issues/45

**Comment by szuecs** [comment]
@abit2 can you check if you can create a or similar to https://github.com/zalando/gin-oauth2/pull/59 that works for your case?
Right now I am not able to do it myself.

**Comment by camaeel** [comment]
This issue makes the google support quite unusable. Could you please provide a fix or at least put information that this module doesn't support google OAuth2 at the moment. 
I lost a lot of time trying to get it working.

**Comment by szuecs** [comment]
@camaeel it would be great if you have time to fix it accordingly similar to it was done for GH in this change: https://github.com/zalando/gin-oauth2/pull/59
