### ISSUE TITLE
Provide mutator methods for google.go's oauth2 config.

### ISSUE THREAD

**Issue by chrishalbert** [zalando/gin-oauth2#76]
I'm using environment variables to handle my secrets. I was wondering if it would be ok for me to submit mutator methods to support another means of setting the `oauth2.Config`'s in [google.go](https://github.com/zalando/gin-oauth2/blob/c0fe6b902235534416bf772c517c65a5b02d998a/google/google.go#L68) specifically. I'd of course want to ensure this remains backwards compatible, so I would only be adding these setters. Below are the functions I'd like to add:

```go
// Usage would be something like:
google.SetClientID(configs.ClientID)
google.SetClientSecret(configs.ClientSecret)
google.SetRedirectURL(redirectURL)
google.SetScopes([]string{gmail.GmailReadonlyScope})
google.SetEndpoint(google.Endpoint)
```

If there's no aversion, I'd be happy to submit an PR - with tests too! :)

**Comment by chrishalbert** [comment]
I didn't see this listed, so I created an issue and went to the PR's to see what feedback I should be aware of, only to find https://github.com/zalando/gin-oauth2/pull/53 🤦 - I can close this, or fix their PR, or open a new one. Whatever it takes to get the addition. Thanks!

**Comment by szuecs** [comment]
Sounds good @chrishalbert . You can also do something like `WithOptions(o Options)` and create all the settings you want to set via the Options struct that you would create.
